#!/bin/bash
# config file for bspwm (bspwmrc) <armin@mutt.email>

# load xrdb settings (Xresources)
xrdb -merge $HOME/.Xresources
xset +fp $HOME/.fonts/

# leave headroom for dzen2 (padding)
$HOME/git/bspwm/bspc config top_padding 0
$HOME/git/bspwm/bspc config bottom_padding 8
$HOME/git/bspwm/bspc config left_padding 0
$HOME/git/bspwm/bspc config right_padding 0
 
# start dzen2 on top of screen
# i3status -c $HOME/.i3status.conf | dzen2 -fg '#b2b2b2' -bg '#262626' -fn verdana-7 &
#  $HOME/bin/bspstatus | dzen2 -fn verdana-7 -bg '#262626' &

# switch trackpad off
# $HOME/bin/tptog

# set border width
$HOME/git/bspwm/bspc config border_width 2

# use gap between windows
$HOME/git/bspwm/bspc config window_gap 24

# define split ratio
$HOME/git/bspwm/bspc config split_ratio 0.50

# define multiple desktops
outputs=($(xrandr -q | grep ' connected ' | cut -d" " -f 1 | tr '\n' ' ' | tr '[:upper:]' '[:lower:]' | tr ' ' '_' | sed 's/_$//g'))

# run specific layout setup script (xrandr)
case "$outputs" in
	lvds1_dp3)
		$HOME/.screenlayout/dp1-single.sh
		sleep 2
    $HOME/git/bspwm/bspc monitor DP1 -d I II III IV V VI VII VIII
		sleep 2
	;;
	*)
		$HOME/git/bspwm/bspc monitor LVDS1 -d I II III IV V VI VII VIII
	;;
esac


# set floating rules for some window types (see xwininfo)
$HOME/git/bspwm/bspc rule -a Gimp floating=on
$HOME/git/bspwm/bspc rule -a Lxappearance floating=on

# monocle
$HOME/git/bspwm/bspc config borderless_monocle true
$HOME/git/bspwm/bspc config gapless_monocle true

# focus options
$HOME/git/bspwm/bspc config focus_by_distance true
$HOME/git/bspwm/bspc config focus_follows_pointer false

# auto alternate
$HOME/git/bspwm/bspc config auto_alternate false

# auto cancel
$HOME/git/bspwm/bspc config auto_cancel true

# colors
$HOME/git/bspwm/bspc config normal_border_color "#002b36"
$HOME/git/bspwm/bspc config active_border_color "#586e75"
$HOME/git/bspwm/bspc config focused_border_color "#657b83"
$HOME/git/bspwm/bspc config presel_border_color "#dc322f"
$HOME/git/bspwm/bspc config urgent_border_color "#2aa198"
$HOME/git/bspwm/bspc config focused_locked_border_color "#464686"

# frame opacity
$HOME/git/bspwm/bspc config normal_frame_opacity 0.9
$HOME/git/bspwm/bspc config focused_frame_opacity 0.9

# initial polarity
$HOME/git/bspwm/bspc config initial_polarity second_child


